name: CI
on:
  push:
    branches:
      - main
jobs:
  tag:
    name: Tag commit
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      tagged: ${{ format(steps.check-tag.outputs.exists == 'false') }}
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Extract version
        run: |
          PACKAGE_VERSION="$(node -p 'require("./package.json").version')"
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
      - name: Check tag exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: check-tag
        with:
          tag: v${{ env.PACKAGE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create tag
        if: steps.check-tag.outputs.exists == 'false'
        uses: pkgdeps/git-tag-action@v2
        with:
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: v
          github_repo: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.PACKAGE_VERSION }}
  publish-gh:
    name: Publish package to GitHub
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: tag
    if: needs.tag.outputs.tagged == 'true'
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          registry-url: https://npm.pkg.github.com
      - name: Install
        run: npm i
      - name: Publish to GitHub
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-npm:
    name: Publish package to NPM
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: tag
    if: needs.tag.outputs.tagged == 'true'
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org
      - name: Install
        run: npm i
      - name: Publish to NPM
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
